site_name: Top of Mind
site_url: https://topofmind.dev
site_description: >-
  Landon's personal life and coding blog

repo_name: LandonTClipp.github.io
repo_url: https://github.com/LandonTClipp/LandonTClipp.github.io
edit_uri: edit/main/docs

theme:
  name: material
  custom_dir: overrides
  font:
    header: Press Start 2P
  icon:
    logo: material/pine-tree
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - toc:
      permalink: true


plugins:
- blog:
    archive: true
    blog_toc: true
    categories_allowed:
      - AWS
      - Career
      - Cloud
      - Golang
      - Grafana
      - Misc
      - Poems
      - Programming
      - Python
      - RV
      - System Administration
      - System Design
    categories_pagination: true
    draft: true
    post_excerpt: required
    post_readtime: true
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    slide_effect: slide
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - custom-skip-class-name
    auto_caption: false
    caption_position: bottom
- meta
- social:
    cards_layout_dir: layouts
    cards_layout: custom
    debug: false
- search
- typeset:
    enabled: true
- open-in-new-tab
nav:
  - index.md
  #- Conventions: conventions.md
  - Blog:
    - blog/index.md
  - Notes:
    - notes/index.md
    - Programming:
      - Bash: notes/programming/bash.md
      - Computer Science: notes/programming/computer-science.md
      - Golang: notes/programming/golang.md
      - Javascript: notes/programming/javascript.md
      - Leetcode: notes/programming/leetcode.md
      - Python: notes/programming/python.md
      - Tools: notes/programming/tools.md
      - Vim: notes/programming/vim.md
      - YAML: notes/programming/yaml.md
    - System Administration:
      - Databases: notes/sysadmin/databases.md
      - Filesystems:
        - notes/sysadmin/cvmfs.md
        - notes/sysadmin/nfs.md
      - Hardware:
        - BMC: notes/sysadmin/bmc.md
        - CPU: notes/sysadmin/cpu.md
        - GPU: notes/sysadmin/gpu.md
        - Misc: notes/sysadmin/misc.md
        - Storage: notes/sysadmin/storage.md
      - Linux: notes/sysadmin/linux.md
      - Networking:
          - General: notes/sysadmin/networking.md
          - OpenStack: notes/sysadmin/openstack.md
          - OSI: notes/sysadmin/osi-model.md
          - SDN: notes/sysadmin/software-defined-networking.md
          - Tracing: notes/sysadmin/network-tracing.md
      - PCIe: notes/sysadmin/pcie.md
      - Repositories: notes/sysadmin/repositories.md
      - Security:
          - HTTP: notes/sysadmin/security.md
          - GPG: notes/sysadmin/gpg.md
      - Systemd: notes/sysadmin/systemd.md
      - Timekeeping: notes/sysadmin/timekeeping.md
      - Virutalization: notes/sysadmin/virtualization.md
    - System Design:
      - Databases: notes/system-design/databases.md
      - "System Design Interview: An Insider's Guide": notes/system-design/system-design-interview-alex-xu.md
      - Tools: notes/system-design/tools.md
  - Misc:
    - Suggested Readings: notes/misc/suggested-readings.md
    - "Word of the Day": notes/misc/word-of-the-day.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LandonTClipp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/landonclipp/
  analytics:
    provider: google
    property: G-F9YVCCMVEX

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - includes

# TODO: Get this working :'(
#hooks:
#  - overrides/hooks/links.py
