site_name: Landon's Blog
site_url: https://LandonTClipp.github.io/
site_description: >-
  Landon's personal life and coding blog

repo_name: LandonTClipp.github.io
repo_url: https://github.com/LandonTClipp/LandonTClipp.github.io

theme:
  name: material
  custom_dir: overrides
  icon: 
    logo: material/pine-tree
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true

plugins:
- blog:
    archive: false
    blog_toc: true
    draft: true
    post_excerpt: required
    post_readtime: true
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    slide_effect: slide
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - custom-skip-class-name
    auto_caption: false
    caption_position: bottom
- meta
- social:
    cards_layout_dir: layouts
    cards_layout: custom
    debug: false
- search
- typeset
- open-in-new-tab

nav:
  - index.md
  - Blog:
    - blog/index.md
  - Golang Topics:
    - Preferred Readings: golang-readings.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LandonTClipp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/landonclipp/
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY