site_name: Landon's Blog
site_url: https://LandonTClipp.github.io/
site_description: >-
  Landon's personal life and coding blog

repo_name: LandonTClipp.github.io
repo_url: https://github.com/LandonTClipp/LandonTClipp.github.io
edit_uri: edit/main/docs

theme:
  name: material
  custom_dir: overrides
  icon: 
    logo: material/pine-tree
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - toc:
      permalink: true


plugins:
- blog:
    archive: true
    blog_toc: true
    categories_allowed:
      - AWS
      - Cloud
      - Golang
      - Grafana
      - Intech Sol Horizon
      - Programming
      - Python
      - RV
      - System Administration
      - System Design
    categories_pagination: true
    draft: true
    post_excerpt: required
    post_readtime: true
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    slide_effect: slide
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - custom-skip-class-name
    auto_caption: false
    caption_position: bottom
- meta
- social:
    cards_layout_dir: layouts
    cards_layout: custom
    debug: false
- search
- typeset:
    enabled: true
- open-in-new-tab

nav:
  - index.md
  - Conventions: conventions.md
  - Blog:
    - blog/index.md
  - Programming:
    - Bash: programming/bash.md
    - Computer Science: programming/computer-science.md
    - Golang: programming/golang.md
    - Javascript: programming/javascript.md
    - Leetcode: programming/leetcode.md
    - Python: programming/python.md
    - Tools: programming/tools.md
    - YAML: programming/yaml.md
  - System Administration:
    - Databases: sysadmin/databases.md
    - Filesystems:
      - sysadmin/cvmfs.md
      - sysadmin/nfs.md
    - Hardware: sysadmin/hardware.md
    - Linux: sysadmin/linux.md
    - Networking: sysadmin/networking.md
    - PCIe: sysadmin/pcie.md
    - Repositories: sysadmin/repositories.md
    - Security: 
        HTTP: sysadmin/security.md
        GPG: sysadmin/gpg.md
    - Systemd: sysadmin/systemd.md
    - Timekeeping: sysadmin/timekeeping.md
    - Virutalization: sysadmin/virtualization.md
  - System Design:
    - Databases: system-design/databases.md
    - "System Design Interview: An Insider's Guide": system-design/system-design-interview-alex-xu.md
    - Tools: system-design/tools.md
  - Misc:
    - Suggested Readings: misc/suggested-readings.md
    - "Word of the Day": misc/word-of-the-day.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LandonTClipp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/landonclipp/
  analytics:
    provider: google
    property: G-F9YVCCMVEX

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - includes

hooks:
  - overrides/hooks/shortcodes.py
