site_name: Landon's Blog
site_url: https://LandonTClipp.github.io/
site_description: >-
  Landon's personal life and coding blog

repo_name: LandonTClipp.github.io
repo_url: https://github.com/LandonTClipp/LandonTClipp.github.io

theme:
  name: material
  custom_dir: overrides
  icon: 
    logo: material/pine-tree
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true


plugins:
- blog:
    archive: false
    blog_toc: true
    draft: true
    post_excerpt: required
    post_readtime: true
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    slide_effect: slide
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - custom-skip-class-name
    auto_caption: false
    caption_position: bottom
- meta
- social:
    cards_layout_dir: layouts
    cards_layout: custom
    debug: false
- search
- typeset
- open-in-new-tab

nav:
  - index.md
  - Blog:
    - blog/index.md
  - Programming:
    - Bash: programming/bash.md
    - Golang: programming/golang.md
    - Leetcode: programming/leetcode.md
    - Preferred Golang Readings: programming/golang-readings.md
    - YAML: programming/yaml.md
  - System Administration:
    - Linux: sysadmin/linux.md
    - Networking: sysadmin/networking.md
    - Systemd: sysadmin/systemd.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LandonTClipp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/landonclipp/
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js